name: RunningPlanet Client CI / CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      # 압축할 파일이 위치한 폴더로 이동합니다
      - name: Navigate to build directory
        run: cd dist

      # dist 폴더를 압축하여 $GITHUB_SHA.zip 파일로 생성합니다
      - name: 📦 Zip project files
        run: zip -r $GITHUB_SHA.zip .

      # 압축된 파일을 S3로 업로드합니다
      - name: 🌎 Access to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 🚛 Upload to S3
        run: aws s3 cp --region ap-northeast-2 $GITHUB_SHA.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/production/$GITHUB_SHA.zip

      # 수정된 압축 파일을 EC2에 배포합니다
      - name: 🚀 Deploy to EC2 with CodeDeploy
        run: aws deploy create-deployment
          --application-name Runple
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name runple
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=production/$GITHUB_SHA.zip
